"""cria tabela click

Revision ID: 3ee7a28741b8
Revises: e5b4b71d7b78
Create Date: 2026-09-19 20:49:07.214982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee7a28741b8'
down_revision = 'e5b4b71d7b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')

    with op.batch_alter_table('link', schema=None) as batch_op:
            batch_op.alter_column(
                'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
            )
    
    with op.batch_alter_table('click', schema=None) as batch_op:
            batch_op.alter_column(
                'clicked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
            )
    
    with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column(
                'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
            )
    # ### end Alembic commands ###
