"""add plano e data_renovacao no user

Revision ID: 860923fe35e0
Revises: d4d78be026ab
Create Date: 2026-10-10 13:04:37.746845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860923fe35e0'
down_revision = 'd4d78be026ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plano', sa.String(length=20), server_default='gratuito', nullable=False))
        batch_op.add_column(sa.Column('data_renovacao', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('data_renovacao')
        batch_op.drop_column('plano')

    # ### end Alembic commands ###
