"""add click_resumo e indice em clicked_at

Revision ID: d4d78be026ab
Revises: 41aaed81757d
Create Date: 2026-10-08 14:52:52.771820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d78be026ab'
down_revision = '41aaed81757d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_resumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('total_cliques', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_id', 'data', name='uq_click_resumo_link_data')
    )
    with op.batch_alter_table('click', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_click_clicked_at'), ['clicked_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_click_clicked_at'))

    op.drop_table('click_resumo')
    # ### end Alembic commands ###
